import click
from typing import Any
from textwrap import dedent
from dotenv import load_dotenv
from litellm import completion
from litellm import AuthenticationError

# Load environment variables from .env file
load_dotenv(override=True)


@click.group()
def cli():
    """AI Toolbox - A command-line tool for AI utilities."""
    pass


@click.command()
def hello():
    """Print a greeting message generated by AI."""
    prompt = dedent("""
                    Generate a friendly and creative greeting message for an AI toolbox CLI application. 
                    Keep it short and fun, under 20 words.
                    """)
    try:
        response: Any = completion(
            model="openai/gpt-4o-mini",
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=0.7
        )
        message = response.choices[0].message.content
        click.echo(message)
    except AuthenticationError as e:
        click.echo("Authentication failed. Check your API key")
    except Exception as e:
        click.echo(f"Error generating message: {e}", err=True)
        click.echo("Hello from the AI toolbox!")


cli.add_command(hello)


if __name__ == "__main__":
    cli()
