import logging
import click
from typing import Any
from textwrap import dedent
from dotenv import load_dotenv
from litellm import completion
from litellm import AuthenticationError
from commands.commit import commit

# Load environment variables from .env file
load_dotenv(override=True)

# Configure logging
logger = logging.getLogger(__name__)


def configure_logging(verbose: bool) -> None:
    """Configure logging for the application.

    Args:
        verbose: If True, set log level to DEBUG; otherwise WARNING.
    """
    level = logging.DEBUG if verbose else logging.WARNING
    logging.basicConfig(
        level=level,
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )
    logger.debug("Logging configured with level: %s", logging.getLevelName(level))


@click.group()
@click.option("-v", "--verbose", is_flag=True, help="Enable debug logging.")
@click.pass_context
def cli(ctx: click.Context, verbose: bool) -> None:
    """AI Toolbox - A command-line tool for AI utilities."""
    ctx.ensure_object(dict)
    ctx.obj["verbose"] = verbose
    configure_logging(verbose)


@click.command()
def hello():
    """Print a greeting message generated by AI."""
    prompt = dedent("""
                    Generate a friendly and creative greeting message for an AI toolbox CLI application. 
                    Keep it short and fun, under 20 words.
                    """)
    try:
        response: Any = completion(
            model="openai/gpt-4o-mini",
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=0.2
        )
        message = response.choices[0].message.content
        click.echo(message)
    except AuthenticationError as e:
        click.echo("Authentication failed. Check your API key")
    except Exception as e:
        click.echo(f"Error generating message: {e}", err=True)
        click.echo("Hello from the AI toolbox!")

@click.command()
def hole():
    """Print a greeting message generated by AI."""
    prompt = dedent("""
                    Generate a friendly and creative greeting message for an AI toolbox CLI application. 
                    Keep it short and fun, under 20 words. Use spanish inclusive language instead of English.
                    """)
    try:
        response: Any = completion(
            model="openai/gpt-4o-mini",
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=2
        )
        message = response.choices[0].message.content
        click.echo(message)
    except AuthenticationError as e:
        click.echo("Authentication failed. Check your API key")
    except Exception as e:
        click.echo(f"Error generating message: {e}", err=True)
        click.echo("Hello from the AI toolbox!")

@click.command()
def holla():
    """Print a greeting message generated by AI."""
    prompt = dedent("""
                    Generate a friendly and creative greeting message for an AI toolbox CLI application. 
                    Keep it short and fun, under 20 words. Use English from "da hood", like a rapper, like Snoop Dogg.
                    """)
    try:
        response: Any = completion(
            model="openai/gpt-4o-mini",
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=2
        )
        message = response.choices[0].message.content
        click.echo(message)
    except AuthenticationError as e:
        click.echo("Authentication failed. Check your API key")
    except Exception as e:
        click.echo(f"Error generating message: {e}", err=True)
        click.echo("Hello from the AI toolbox!")

@click.command()
def hollah():
    """Print a greeting message generated by AI."""
    prompt = dedent("""
                    Generate a friendly and creative greeting message for an AI toolbox CLI application. 
                    Keep it short and fun, under 20 words. Use malformed Spanish as if it was a gringo tourist in Mexico.
                    """)
    try:
        response: Any = completion(
            model="openai/gpt-4o-mini",
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=2
        )
        message = response.choices[0].message.content
        click.echo(message)
    except AuthenticationError as e:
        click.echo("Authentication failed. Check your API key")
    except Exception as e:
        click.echo(f"Error generating message: {e}", err=True)
        click.echo("Hello from the AI toolbox!")

@click.command()
def kiubo():
    """Print a greeting message generated by AI."""
    prompt = dedent("""
                    Generate a friendly and creative greeting message for an AI toolbox CLI application. 
                    Keep it short and fun, under 20 words. Write it in an informal Mexican Spanish. Use Mexican slang.
                    """)
    try:
        response: Any = completion(
            model="openai/gpt-4o-mini",
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=1.9
        )
        message = response.choices[0].message.content
        click.echo(message)
    except AuthenticationError as e:
        click.echo("Authentication failed. Check your API key")
    except Exception as e:
        click.echo(f"Error generating message: {e}", err=True)
        click.echo("Hello from the AI toolbox!")



cli.add_command(hello)
cli.add_command(hole)
cli.add_command(holla)
cli.add_command(hollah)
cli.add_command(kiubo)
cli.add_command(commit)


if __name__ == "__main__":
    cli()
