import click
from typing import Any
from textwrap import dedent
from dotenv import load_dotenv
from litellm import completion
from litellm import AuthenticationError
from commands.commit import commit

# Load environment variables from .env file
load_dotenv(override=True)


@click.group()
def cli():
    """AI Toolbox - A command-line tool for AI utilities."""
    pass


@click.command()
def hello():
    """Print a greeting message generated by AI."""
    prompt = dedent("""
                    Generate a friendly and creative greeting message for an AI toolbox CLI application. 
                    Keep it short and fun, under 20 words.
                    """)
    try:
        response: Any = completion(
            model="openai/gpt-4o-mini",
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=0.2
        )
        message = response.choices[0].message.content
        click.echo(message)
    except AuthenticationError as e:
        click.echo("Authentication failed. Check your API key")
    except Exception as e:
        click.echo(f"Error generating message: {e}", err=True)
        click.echo("Hello from the AI toolbox!")

@click.command()
def hole():
    """Print a greeting message generated by AI."""
    prompt = dedent("""
                    Generate a friendly and creative greeting message for an AI toolbox CLI application. 
                    Keep it short and fun, under 20 words. Use spanish inclusive language instead of English.
                    """)
    try:
        response: Any = completion(
            model="openai/gpt-4o-mini",
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=2
        )
        message = response.choices[0].message.content
        click.echo(message)
    except AuthenticationError as e:
        click.echo("Authentication failed. Check your API key")
    except Exception as e:
        click.echo(f"Error generating message: {e}", err=True)
        click.echo("Hello from the AI toolbox!")

@click.command()
def holla():
    """Print a greeting message generated by AI."""
    prompt = dedent("""
                    Generate a friendly and creative greeting message for an AI toolbox CLI application. 
                    Keep it short and fun, under 20 words. Use English from "da hood", like a rapper, like Snoop Dogg.
                    """)
    try:
        response: Any = completion(
            model="openai/gpt-4o-mini",
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=2
        )
        message = response.choices[0].message.content
        click.echo(message)
    except AuthenticationError as e:
        click.echo("Authentication failed. Check your API key")
    except Exception as e:
        click.echo(f"Error generating message: {e}", err=True)
        click.echo("Hello from the AI toolbox!")

@click.command()
def hollah():
    """Print a greeting message generated by AI."""
    prompt = dedent("""
                    Generate a friendly and creative greeting message for an AI toolbox CLI application. 
                    Keep it short and fun, under 20 words. Use malformed Spanish as if it was a gringo tourist in Mexico.
                    """)
    try:
        response: Any = completion(
            model="openai/gpt-4o-mini",
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=2
        )
        message = response.choices[0].message.content
        click.echo(message)
    except AuthenticationError as e:
        click.echo("Authentication failed. Check your API key")
    except Exception as e:
        click.echo(f"Error generating message: {e}", err=True)
        click.echo("Hello from the AI toolbox!")

@click.command()
def kiubo():
    """Print a greeting message generated by AI."""
    prompt = dedent("""
                    Generate a friendly and creative greeting message for an AI toolbox CLI application. 
                    Keep it short and fun, under 20 words. Write it in an informal Mexican Spanish. Use Mexican slang.
                    """)
    try:
        response: Any = completion(
            model="openai/gpt-4o-mini",
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=1.9
        )
        message = response.choices[0].message.content
        click.echo(message)
    except AuthenticationError as e:
        click.echo("Authentication failed. Check your API key")
    except Exception as e:
        click.echo(f"Error generating message: {e}", err=True)
        click.echo("Hello from the AI toolbox!")



cli.add_command(hello)
cli.add_command(hole)
cli.add_command(holla)
cli.add_command(hollah)
cli.add_command(kiubo)
cli.add_command(commit)


if __name__ == "__main__":
    cli()
